concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
jobs:
  flake8:
    uses: steinwurf/flake8-action/.github/workflows/action.yml@2.0.0
    with:
      excluded_errors: F632,F821
name: Flake8
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch: null
